### ISSUE TITLE
Add code hooks for HFL

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/LevelTemplate#3]
While we plan to reference HFL via the OP2MissionSDK submodule, HFL must be activated by a call in the main function, typically placed in dllMain, separate from what we call LevelMain.

**Comment by DanRStevens** [comment]
Are you proposing calling HFLInit, even for projects that don't use HFL? Or perhaps providing a commented out template line?

Alternatively, perhaps we can modify HFL so it doesn't need an `HFLInit` call. It works similar to OP2Internal, so if we update the mechanism there, perhaps the same can be done for HFL. In particular, the init method is just initializing pointers to known locations in Outpost2.exe, which of course depends on the base address of the Outpost2.exe module (which can be relocated).

Ideally, things should work as transparently as possible, with little need for end users to adjust settings. Mind you, HFL uses more advanced memory hacking concepts, and if they're using HFL, they may know a little more about what they're doing.

**Comment by Brett208** [comment]
I would like to add the following which sets up for both HFL cleanup and access to hinstDLL for having a modal dialog box on colony games.

```C++
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include "HFL/Source/HFL.h"

BOOL APIENTRY DllMain(HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpvReserved)
{
        if (fdwReason == DLL_PROCESS_DETACH)
	{
		HFLCleanup();
	}

	return TRUE;
}
```

Also Add

```C++
#include "HFL/Source/HFL.h"

Export int InitProc()
{
	HFLInit();
}
```

If we don't add it, people are probably going to get confused on why HFL is included in OP2MissionSDK and properly referenced by the LevelMain project but doesn't work. 

I don't believe knowledge of memory hacking is needed to use HFL, only to modify it. I use HFL in most of my missions but only have a hazy idea how memory hacking works.

-Brett

**Comment by DanRStevens** [comment]
This makes me slightly queasy, but yes, it makes sense to make this easier to use, and have correct by default behavior. We should add comments though. If level designers are not using those features, they should know it is safe to comment out or remove those lines. As there are two separate places which are relevant, they should probably cross reference each other's location.

It almost feels like HFL should have a global object to hang this methods off of. Then initialization of the global can init the library, and destruction of the global can cleanup. In particular, initialization and destruction would then be controlled by a single point, where the global is defined. But, that's a thought for another day.

**Comment by Brett208** [comment]
Slight update. Realized HFL can be initialized in DLLMain instead of InitProc. In fact it creates bugs for non-multiplayer scenarios to initialize in InitProc during save/load.

**Comment by DanRStevens** [comment]
Thank you for tracking this, I'd already forgotten about it.

I like how calling `HFLInit()` from `DllMain` makes the code more symmetric with the `HFLCleanup()` call. It's also more hidden away from areas where the user is likely to edit stuff or care about.
