### ISSUE TITLE
Upgrade Solution and Project files

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/LevelTemplate#4]
Solution and project files should be upgraded from VS2010 to VS2017.

Related, we should standardize on a single set of Release settings. These settings should be called simply "Release". As level code is not speed critical, and there can be a lot of them, I recommend the release settings be optimized for small size rather than for speed.

**Comment by Brett208** [comment]
Dependent on updating submodules first

**Comment by Brett208** [comment]
Will tackle this once OP2MissionSDK 4.0.0 is released. OP2Helper's new project settings are required and contained in 4.0.0.

**Comment by DanRStevens** [comment]
I'm not sure I understand the comment about OP2Helper's new project settings.

Looks like things have settled on "Release" for the configuration name, so that part is now solved.

Main issue remaining is upgrading the project files, which are mixed versions.

**Comment by Brett208** [comment]
My last comment was poorly informed and written. This change has now been made and all projects are on VS2017 with Release and Debug configurations. I'm going to close the issue.

Sorry for the confusion.

**Comment by DanRStevens** [comment]
Hmm, my last comment may have been in error too. What about the solution files? That's what I was just looking at when I noticed mixed versions:
```
Microsoft Visual Studio Solution File, Format Version 11.00
# Visual C++ Express 2010
```

```
Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio 15
VisualStudioVersion = 15.0.28307.168
MinimumVisualStudioVersion = 10.0.40219.1
```
