### ISSUE TITLE
Make LevelTemplate a Colony Game instead of Multiplayer

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/LevelTemplate#7]
I was considering making LevelTemplate compile as a colony game. It is easier to test via Outpost 2. Otherwise I have to bring up multiple copies of Outpost 2 and make a network connection between them just to test the template plays nice with Outpost 2.

I also think for someone initially playing with Outpost 2 mission coding, they should start with a colony game for the same reasons. 

Wanted to post here to see if anyone objected before doing as it is sort of a gray issue.

**Comment by DanRStevens** [comment]
Do it.

I think we briefly discussed this idea somewhere else a while back. The level template makes way more sense setup as a Colony game.
